# Libraries

In [ ]:
import sys
my_framework_path = '/home/wmpjrufg/Documents/metapy' # PC prof. wanderlei at umn
my_framework_path = r'C:\git-projetos\metapy' # PC prof. wanderlei
sys.path.append(my_framework_path)
from metapy_toolbox import *

# GA tests

In [4]:
x_ini = [
            [0.5, 3.0, 1.0],
            [1.5, 8.0, 1.0],
            [2.5, 2.5, 1.0],
            [3.5, 3.5, 1.0],
            [3.5, 7.5, 2.0]
        ]
paras = {
            
        }
n_gen = 50
frame, best, report = grey_wolf_optimizer_01(sphere, n_gen, paras, x_ini, [0]*3, [5]*3)
best

,ITER,OF EVALUATIONS,BEST ID,X_BEST_0,X_BEST_1,X_BEST_2,OF BEST,WORST ID,X_WORST_0,X_WORST_1,X_WORST_2,OF WORST,MEAN OF,STD OF,TIME CONSUMPTION (s),DIVERSITY,DIVERSITY(XPL) %,DIVERSITY(XPT) %
0,0,5,0,0.5,3.0,1.0,10.25,4,3.5,7.5,2.0,72.5,37.8,29.883838,0.000035,2.353333,100.000000,0.000000
1,1,10,0,0.0,0.4311,2.278091,5.375547,4,4.143964,3.526527,0.0,29.608827,19.796875,10.043628,0.000059,1.999856,84.979729,15.020271
2,2,15,3,0.0,1.024054,0.125758,1.064502,4,4.143964,3.526527,0.0,29.608827,10.756686,11.137617,0.000077,1.138478,48.377259,51.622741
3,3,20,0,0.480448,0.0,0.0,0.23083,4,0.0,0.0,3.988278,15.906364,4.841367,6.761754,0.000092,1.028298,43.695389,56.304611
4,4,25,1,0.257384,0.0,0.0,0.066246,4,0.855417,2.215635,0.0,5.640777,1.266513,2.446252,0.000104,0.301056,12.792750,87.207250
5,5,30,4,0.0,0.0,0.0,0.0,2,0.0,0.0,0.485511,0.235721,0.121244,0.100932,0.000117,0.020576,0.874334,99.125666
6,6,35,4,0.0,0.0,0.0,0.0,0,0.335902,0.254926,0.05574,0.180924,0.055194,0.073685,0.000127,0.008624,0.366459,99.633541
7,7,40,4,0.0,0.0,0.0,0.0,1,0.138123,0.021179,0.155955,0.043848,0.014451,0.017721,0.000139,0.002838,0.120595,99.879405
8,8,45,4,0.0,0.0,0.0,0.0,1,0.0,0.118437,0.0,0.014027,0.00435,0.006066,0.000148,0.000951,0.040411,99.959589
9,9,50,4,0.0,0.0,0.0,0.0,0,0.043167,0.048346,0.049231,0.006624,0.002079,0.002784,0.000157,0.000417,0.017720,99.982280
10,10,55,2,0.0,0.0,0.0,0.0,1,0.0044,0.0,0.013511,0.000202,0.000046,0.000088,0.000168,0.000012,0.000510,99.999490
11,11,60,2,0.0,0.0,0.0,0.0,1,0.001303,0.005362,0.0,0.00003,0.000006,0.000014,0.000177,0.000002,0.000085,99.999915
12,12,65,2,0.0,0.0,0.0,0.0,1,0.0,0.003169,0.0,0.00001,0.000002,0.000004,0.000185,0.000001,0.000042,99.999958
13,13,70,2,0.0,0.0,0.0,0.0,1,0.0,0.0,0.000749,0.000001,0.0,0.0,0.000194,0.000000,0.000000,100.000000
14,14,75,2,0.0,0.0,0.0,0.0,1,0.000268,0.0,0.0,0.0,0.0,0.0,0.000203,0.000000,0.000000,100.000000
15,15,80,2,0.0,0.0,0.0,0.0,1,0.000012,0.00011,0.000065,0.0,0.0,0.0,0.000211,0.000000,0.000000,100.000000
16,16,85,2,0.0,0.0,0.0,0.0,1,0.000028,0.000094,0.0,0.0,0.0,0.0,0.000222,0.000000,0.000000,100.000000
17,17,90,2,0.0,0.0,0.0,0.0,0,0.000011,0.000028,0.000032,0.0,0.0,0.0,0.000231,0.000000,0.000000,100.000000
18,18,95,2,0.0,0.0,0.0,0.0,0,0.00003,0.000013,0.0,0.0,0.0,0.0,0.000239,0.000000,0.000000,100.000000
19,19,100,2,0.0,0.0,0.0,0.0,1,0.000003,0.0,0.0,0.0,0.0,0.0,0.000248,0.000000,0.000000,100.000000
20,20,105,2,0.0,0.0,0.0,0.0,1,0.000001,0.0,0.000002,0.0,0.0,0.0,0.000262,0.000000,0.000000,100.000000
21,21,110,1,0.0,0.0,0.0,0.0,3,0.000001,0.000001,0.0,0.0,0.0,0.0,0.000270,0.000000,0.000000,100.000000
22,22,115,1,0.0,0.0,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.000278,0.000000,0.000000,100.000000
23,23,120,1,0.0,0.0,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.000287,0.000000,0.000000,100.000000
24,24,125,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000295,0.000000,0.000000,100.000000
25,25,130,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000303,0.000000,0.000000,100.000000
26,26,135,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000311,0.000000,0.000000,100.000000
27,27,140,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000320,0.000000,0.000000,100.000000
28,28,145,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000328,0.000000,0.000000,100.000000
29,29,150,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000336,0.000000,0.000000,100.000000
30,30,155,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000344,0.000000,0.000000,100.000000
31,31,160,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000352,0.000000,0.000000,100.000000
32,32,165,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000361,0.000000,0.000000,100.000000
33,33,170,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000369,0.000000,0.000000,100.000000
34,34,175,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000377,0.000000,0.000000,100.000000
35,35,180,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000385,0.000000,0.000000,100.000000
36,36,185,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000393,0.000000,0.000000,100.000000
37,37,190,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000402,0.000000,0.000000,100.000000
38,38,195,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000410,0.000000,0.000000,100.000000
39,39,200,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000418,0.000000,0.000000,100.000000
40,40,205,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000426,0.000000,0.000000,100.000000
41,41,210,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000434,0.000000,0.000000,100.000000
42,42,215,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000443,0.000000,0.000000,100.000000
43,43,220,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000451,0.000000,0.000000,100.000000
44,44,225,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000459,0.000000,0.000000,100.000000
45,45,230,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000467,0.000000,0.000000,100.000000
46,46,235,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000476,0.000000,0.000000,100.000000
47,47,240,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000484,0.000000,0.000000,100.000000
48,48,245,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000492,0.000000,0.000000,100.000000
49,49,250,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000500,0.000000,0.000000,100.000000
50,50,255,1,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000508,0.000000,0.000000,100.000000

In [3]:
frame.head(20)

,ID,ITER,X_0,X_1,X_2,OF,FIT,OF EVALUATIONS,TIME CONSUMPTION (s),REPORT,P_X_BEST_0,P_X_BEST_1,P_X_BEST_2,P_OF_BEST,A,DIVERSITY
0,0,0,0.500000,3.000000,1.000000,10.250000,0.088889,1,0.000013,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,0.500000,3.000000,1.000000,10.250000,2.0,2.353333
1,1,0,1.500000,8.000000,1.000000,67.250000,0.014652,1,0.000007,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,1.500000,8.000000,1.000000,67.250000,2.0,2.353333
2,2,0,2.500000,2.500000,1.000000,13.500000,0.068966,1,0.000005,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.500000,2.500000,1.000000,13.500000,2.0,2.353333
3,3,0,3.500000,3.500000,1.000000,25.500000,0.037736,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,3.500000,3.500000,1.000000,25.500000,2.0,2.353333
4,4,0,3.500000,7.500000,2.000000,72.500000,0.013605,1,0.000003,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,3.500000,7.500000,2.000000,72.500000,2.0,2.353333
5,0,1,0.500000,3.000000,1.000000,10.250000,0.088889,1,0.000013,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,0.500000,3.000000,1.000000,10.250000,2.0,2.594260
6,1,1,2.417519,0.852604,5.000000,31.571329,0.030702,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.417519,0.852604,5.000000,31.571329,NaN,2.594260
7,2,1,2.500000,2.500000,1.000000,13.500000,0.068966,1,0.000005,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.500000,2.500000,1.000000,13.500000,2.0,2.594260
8,3,1,2.942614,0.436729,0.000000,8.849707,0.101526,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.942614,0.436729,0.000000,8.849707,NaN,2.594260
9,4,1,5.000000,5.000000,2.531951,56.410776,0.017418,1,0.000003,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,5.000000,5.000000,2.531951,56.410776,NaN,2.594260
10,0,2,1.248960,1.286278,0.000000,3.214412,0.237281,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,1.248960,1.286278,0.000000,3.214412,NaN,1.294635
11,1,2,5.000000,0.000000,0.608768,25.370598,0.037921,1,0.000003,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,5.000000,0.000000,0.608768,25.370598,NaN,1.294635
12,2,2,2.500000,2.500000,1.000000,13.500000,0.068966,1,0.000005,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.500000,2.500000,1.000000,13.500000,2.0,1.294635
13,3,2,2.942614,0.436729,0.000000,8.849707,0.101526,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,2.942614,0.436729,0.000000,8.849707,NaN,1.294635
14,4,2,3.315293,0.000000,3.306637,21.925019,0.043620,1,0.000002,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,3.315293,0.000000,3.306637,21.925019,NaN,1.294635
15,0,3,1.248960,1.286278,0.000000,3.214412,0.237281,1,0.000004,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,1.248960,1.286278,0.000000,3.214412,NaN,1.347830
16,1,3,0.000000,2.781892,2.163678,12.420429,0.074513,1,0.000005,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,0.000000,2.781892,2.163678,12.420429,NaN,1.347830
17,2,3,3.061738,0.000000,0.338263,9.488665,0.095341,1,0.000003,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,3.061738,0.000000,0.338263,9.488665,NaN,1.347830
18,3,3,1.370266,0.815679,1.601282,5.107063,0.163745,1,0.000002,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,1.370266,0.815679,1.601282,5.107063,NaN,1.347830
19,4,3,3.315293,0.000000,3.306637,21.925019,0.043620,1,0.000002,Gray Wolf Algorithm\niteration: 1\n Agent id: ...,3.315293,0.000000,3.306637,21.925019,NaN,1.347830