# Libraries

In [ ]:
import sys
my_framework_path = '/home/wmpjrufg/Documents/metapy' # PC prof. wanderlei at umn
my_framework_path = r'C:\git-projetos\metapy' # PC prof. wanderlei
sys.path.append(my_framework_path)
from metapy_toolbox import *

# GA tests

In [2]:
x_ini = [
            [0.5, 3.0, 1.0],
            [1.5, 8.0, 1.0],
            [2.5, 2.5, 1.0],
            [3.5, 3.5, 1.0]
        ]
paras = {
            'selection': 'roulette wheel',
            'crossover': {'type': 'blx-alpha', 'crossover rate (%)': 90},
            'mutation': {'type': 'random walk', 'mutation rate (%)': 20, 'params': {'pdf': 'gaussian', 'cov (%)': 10}}
        }
n_gen = 50
rob = {'n evals': 10, 'perturbation (%)': 5}  
frame, best, report = genetic_algorithm_01(sphere, n_gen, paras, x_ini, [0]*3, [5]*3, robustness=rob)
best

,ITER,OF EVALUATIONS,BEST ID,X_BEST_0,X_BEST_1,X_BEST_2,OF BEST,WORST ID,X_WORST_0,X_WORST_1,X_WORST_2,OF WORST,MEAN OF,STD OF,TIME CONSUMPTION (s),DIVERSITY,DIVERSITY_XPL (%),DIVERSITY_XPT (%)
0,0,4,0,0.5,3.0,1.0,10.25,1,1.5,8.0,1.0,67.25,29.125,26.249206,0.000019,2.020833,100.000000,0.000000
1,1,50,1,0.0,1.226239,1.0,2.514092,2,2.5,2.5,1.0,13.563704,6.557026,5.075622,0.000029,0.446931,22.116177,77.883823
2,2,96,0,0.0,0.391944,1.0,1.157684,2,2.5,2.5,1.0,13.514844,4.661192,5.916177,0.000037,0.571886,28.299518,71.700482
3,3,144,0,0.0,0.0,1.0,0.98784,2,0.0,0.760558,1.0,1.595438,1.173363,0.285234,0.000045,0.032175,1.592165,98.407835
4,4,192,1,0.0,0.0,1.0,0.988553,3,0.0,0.223353,1.0,1.064073,1.02191,0.035722,0.000053,0.003118,0.154293,99.845707
5,5,238,1,0.0,0.0,1.0,0.977287,0,0.0,0.0,1.0,1.041843,1.010678,0.033525,0.000058,0.003118,0.154293,99.845707
6,6,284,0,0.0,0.0,1.0,0.96576,2,0.0,0.0,1.0,1.009057,0.978747,0.020334,0.000063,0.000000,0.000000,100.000000
7,7,330,1,0.0,0.0,1.0,0.9713,2,0.0,0.0,1.0,1.029699,1.002209,0.024671,0.000066,0.000000,0.000000,100.000000
8,8,377,2,0.0,0.0,0.976911,0.950986,3,0.0,0.0,1.0,1.027652,0.995214,0.032193,0.000071,0.000033,0.001633,99.998367
9,9,425,3,0.0,0.0,0.9581,0.889518,1,0.0,0.0,1.0,1.019014,0.935423,0.05748,0.000075,0.000113,0.005592,99.994408
10,10,475,1,0.0,0.0,0.841519,0.734084,3,0.0,0.0,0.9581,0.958935,0.885882,0.102469,0.000081,0.000815,0.040330,99.959670
11,11,525,0,0.0,0.0,0.732014,0.538009,3,0.0,0.0,0.95467,0.907347,0.654515,0.173867,0.000087,0.002743,0.135736,99.864264
12,12,574,3,0.0,0.0,0.531797,0.281834,0,0.0,0.0,0.703065,0.485021,0.43106,0.099551,0.000092,0.001695,0.083876,99.916124
13,13,624,3,0.0,0.0,0.454212,0.204828,2,0.0,0.0,0.685322,0.478958,0.383347,0.123472,0.000098,0.002962,0.146573,99.853427
14,14,671,1,0.0,0.0,0.382577,0.146307,0,0.0,0.0,0.683743,0.475907,0.320162,0.170269,0.000101,0.006055,0.299629,99.700371
15,15,720,1,0.0,0.0,0.161424,0.02603,0,0.0,0.0,0.68222,0.465554,0.183751,0.195034,0.000108,0.012126,0.600050,99.399950
16,16,768,0,0.0,0.0,0.0,0.0,2,0.0,0.0,0.056528,0.003211,0.000803,0.001606,0.000114,0.000200,0.009897,99.990103
17,17,815,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000118,0.000000,0.000000,100.000000
18,18,861,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000121,0.000000,0.000000,100.000000
19,19,910,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000124,0.000000,0.000000,100.000000
20,20,959,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000127,0.000000,0.000000,100.000000
21,21,1006,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000129,0.000000,0.000000,100.000000
22,22,1054,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000132,0.000000,0.000000,100.000000
23,23,1102,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000135,0.000000,0.000000,100.000000
24,24,1150,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000138,0.000000,0.000000,100.000000
25,25,1197,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000140,0.000000,0.000000,100.000000
26,26,1247,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000143,0.000000,0.000000,100.000000
27,27,1293,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000146,0.000000,0.000000,100.000000
28,28,1341,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000149,0.000000,0.000000,100.000000
29,29,1389,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000151,0.000000,0.000000,100.000000
30,30,1438,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000154,0.000000,0.000000,100.000000
31,31,1485,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000157,0.000000,0.000000,100.000000
32,32,1533,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000160,0.000000,0.000000,100.000000
33,33,1581,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
34,34,1625,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
35,35,1674,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
36,36,1724,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
37,37,1773,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
38,38,1823,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
39,39,1867,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
40,40,1916,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
41,41,1966,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
42,42,2015,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
43,43,2063,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
44,44,2112,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
45,45,2161,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
46,46,2209,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
47,47,2255,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
48,48,2302,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
49,49,2349,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000
50,50,2397,0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.000161,0.000000,0.000000,100.000000

In [4]:
frame

,ID,ITER,X_0,X_1,X_2,OF,FIT,OF EVALUATIONS,TIME CONSUMPTION (s),REPORT,P_X_BEST_0,P_X_BEST_1,P_X_BEST_2,P_OF_BEST
0,0,0,0.500000,3.000000,1.0,10.250000,0.088889,1,0.000068,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.500000,3.000000,1.0,10.250000
1,1,0,1.500000,8.000000,1.0,67.250000,0.014652,1,0.000049,Genetic Algorithm\niteration: 1\n Agent id: 0\...,1.500000,8.000000,1.0,67.250000
2,2,0,2.500000,2.500000,1.0,13.500000,0.068966,1,0.000016,Genetic Algorithm\niteration: 1\n Agent id: 0\...,2.500000,2.500000,1.0,13.500000
3,3,0,3.500000,3.500000,1.0,25.500000,0.037736,1,0.000022,Genetic Algorithm\niteration: 1\n Agent id: 0\...,3.500000,3.500000,1.0,25.500000
4,0,1,0.179826,2.564609,1.0,7.558519,0.117093,12,0.000037,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.179826,2.564609,1.0,7.558519
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,3,49,0.000000,0.000000,0.0,0.000000,1.000000,12,0.000000,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.000000,0.000000,0.0,0.000000
200,0,50,0.000000,0.000000,0.0,0.000000,1.000000,12,0.000000,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.000000,0.000000,0.0,0.000000
201,1,50,0.000000,0.000000,0.0,0.000000,1.000000,12,0.000000,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.000000,0.000000,0.0,0.000000
202,2,50,0.000000,0.000000,0.0,0.000000,1.000000,12,0.000000,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.000000,0.000000,0.0,0.000000
203,3,50,0.000000,0.000000,0.0,0.000000,1.000000,12,0.000000,Genetic Algorithm\niteration: 1\n Agent id: 0\...,0.000000,0.000000,0.0,0.000000

In [8]:
x_ini = [
            [0.0],
            [7.0],
            [25.0]
        ]
paras = {
            'selection': 'roulette wheel',
            'crossover': {'type': 'blx-alpha', 'crossover rate (%)': 90},
            'mutation': {'type': 'random walk', 'mutation rate (%)': 20, 'params': {'pdf': 'gaussian', 'cov (%)': 10}}
        }
n_gen = 20
frame, best, report = genetic_algorithm_01(active_learning_example, n_gen, paras, x_ini, [0], [25])
best

,ITER,OF EVALUATIONS,BEST ID,X_BEST_0,OF BEST,WORST ID,X_WORST_0,OF WORST,MEAN OF,STD OF,TIME CONSUMPTION (s)
0,0,3,0,0.0,3.141276,2,25.0,11.429195,5.903916,4.785032,0.018127
1,1,11,0,0.0,3.141276,0,0.0,3.141276,3.141276,0.0,0.036249
2,2,18,1,13.892716,-1.722522,0,0.0,3.141276,1.52001,2.808115,0.054352
3,3,23,1,17.76929,-14.06279,0,0.0,3.141276,-2.593412,9.932772,0.072458
4,4,30,1,19.251825,-15.040954,0,0.0,3.141276,-2.919467,10.497516,0.090550
5,5,36,1,19.251825,-15.040954,0,0.0,3.141276,-8.275488,9.943556,0.108653
6,6,42,2,19.231617,-15.051403,0,0.0,3.141276,-8.983694,10.500533,0.126797
7,7,47,2,19.225741,-15.054311,0,0.0,3.141276,-8.984663,10.501373,0.144887
8,8,53,1,19.205495,-15.063876,0,0.0,3.141276,-8.993217,10.50878,0.162984
9,9,59,2,19.193556,-15.069189,0,0.0,3.141276,-8.998727,10.513552,0.181082
10,10,65,1,19.1921,-15.06982,0,0.0,3.141276,-8.999284,10.514033,0.199180
11,11,69,2,19.191472,-15.070091,0,0.0,3.141276,-8.999576,10.514286,0.199194
12,12,74,1,19.191282,-15.070173,0,0.0,3.141276,-8.999679,10.514376,0.199209
13,13,81,1,19.191272,-15.070177,0,0.0,3.141276,-8.999692,10.514387,0.199226
14,14,87,2,19.191264,-15.070181,0,0.0,3.141276,-8.999695,10.514389,0.199245
15,15,91,2,19.191262,-15.070182,0,20.100157,-13.961292,-14.700551,0.640217,0.199269
16,16,97,0,18.737792,-15.093031,1,19.191261,-15.070182,-15.077799,0.013191,0.199307
17,17,101,0,18.737792,-15.093031,1,19.191261,-15.070182,-15.077799,0.013191,0.199328
18,18,108,0,18.737792,-15.093031,2,19.191251,-15.070186,-15.077801,0.013189,0.199357
19,19,112,0,18.737792,-15.093031,2,19.191251,-15.070186,-15.077801,0.013189,0.199377
20,20,116,0,18.737792,-15.093031,2,19.191251,-15.070186,-15.077801,0.013189,0.199394